package com.kuaidixx.kuaidixx.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_num
     *
     * @mbg.generated
     */
    private Long orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.price_type
     *
     * @mbg.generated
     */
    private Integer priceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.payment_time
     *
     * @mbg.generated
     */
    private Date paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.close_time
     *
     * @mbg.generated
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.item_type
     *
     * @mbg.generated
     */
    private String itemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.item_volume
     *
     * @mbg.generated
     */
    private Double itemVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.item_weight
     *
     * @mbg.generated
     */
    private Double itemWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipients_address
     *
     * @mbg.generated
     */
    private String recipientsAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipients_full_address
     *
     * @mbg.generated
     */
    private String recipientsFullAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipients_landline_number
     *
     * @mbg.generated
     */
    private String recipientsLandlineNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipients_mobile
     *
     * @mbg.generated
     */
    private String recipientsMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipients_name
     *
     * @mbg.generated
     */
    private String recipientsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.send_address
     *
     * @mbg.generated
     */
    private String sendAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.send_full_address
     *
     * @mbg.generated
     */
    private String sendFullAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sender_landline_number
     *
     * @mbg.generated
     */
    private String senderLandlineNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sender_mobile
     *
     * @mbg.generated
     */
    private String senderMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sender_name
     *
     * @mbg.generated
     */
    private String senderName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_num
     *
     * @return the value of order.order_num
     *
     * @mbg.generated
     */
    public Long getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_num
     *
     * @param orderNum the value for order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(Long orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.price
     *
     * @return the value of order.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.price
     *
     * @param price the value for order.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.price_type
     *
     * @return the value of order.price_type
     *
     * @mbg.generated
     */
    public Integer getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.price_type
     *
     * @param priceType the value for order.price_type
     *
     * @mbg.generated
     */
    public void setPriceType(Integer priceType) {
        this.priceType = priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.payment_time
     *
     * @return the value of order.payment_time
     *
     * @mbg.generated
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.payment_time
     *
     * @param paymentTime the value for order.payment_time
     *
     * @mbg.generated
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.end_time
     *
     * @return the value of order.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.end_time
     *
     * @param endTime the value for order.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.close_time
     *
     * @return the value of order.close_time
     *
     * @mbg.generated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.close_time
     *
     * @param closeTime the value for order.close_time
     *
     * @mbg.generated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.item_type
     *
     * @return the value of order.item_type
     *
     * @mbg.generated
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.item_type
     *
     * @param itemType the value for order.item_type
     *
     * @mbg.generated
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.item_volume
     *
     * @return the value of order.item_volume
     *
     * @mbg.generated
     */
    public Double getItemVolume() {
        return itemVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.item_volume
     *
     * @param itemVolume the value for order.item_volume
     *
     * @mbg.generated
     */
    public void setItemVolume(Double itemVolume) {
        this.itemVolume = itemVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.item_weight
     *
     * @return the value of order.item_weight
     *
     * @mbg.generated
     */
    public Double getItemWeight() {
        return itemWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.item_weight
     *
     * @param itemWeight the value for order.item_weight
     *
     * @mbg.generated
     */
    public void setItemWeight(Double itemWeight) {
        this.itemWeight = itemWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipients_address
     *
     * @return the value of order.recipients_address
     *
     * @mbg.generated
     */
    public String getRecipientsAddress() {
        return recipientsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipients_address
     *
     * @param recipientsAddress the value for order.recipients_address
     *
     * @mbg.generated
     */
    public void setRecipientsAddress(String recipientsAddress) {
        this.recipientsAddress = recipientsAddress == null ? null : recipientsAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipients_full_address
     *
     * @return the value of order.recipients_full_address
     *
     * @mbg.generated
     */
    public String getRecipientsFullAddress() {
        return recipientsFullAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipients_full_address
     *
     * @param recipientsFullAddress the value for order.recipients_full_address
     *
     * @mbg.generated
     */
    public void setRecipientsFullAddress(String recipientsFullAddress) {
        this.recipientsFullAddress = recipientsFullAddress == null ? null : recipientsFullAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipients_landline_number
     *
     * @return the value of order.recipients_landline_number
     *
     * @mbg.generated
     */
    public String getRecipientsLandlineNumber() {
        return recipientsLandlineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipients_landline_number
     *
     * @param recipientsLandlineNumber the value for order.recipients_landline_number
     *
     * @mbg.generated
     */
    public void setRecipientsLandlineNumber(String recipientsLandlineNumber) {
        this.recipientsLandlineNumber = recipientsLandlineNumber == null ? null : recipientsLandlineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipients_mobile
     *
     * @return the value of order.recipients_mobile
     *
     * @mbg.generated
     */
    public String getRecipientsMobile() {
        return recipientsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipients_mobile
     *
     * @param recipientsMobile the value for order.recipients_mobile
     *
     * @mbg.generated
     */
    public void setRecipientsMobile(String recipientsMobile) {
        this.recipientsMobile = recipientsMobile == null ? null : recipientsMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipients_name
     *
     * @return the value of order.recipients_name
     *
     * @mbg.generated
     */
    public String getRecipientsName() {
        return recipientsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipients_name
     *
     * @param recipientsName the value for order.recipients_name
     *
     * @mbg.generated
     */
    public void setRecipientsName(String recipientsName) {
        this.recipientsName = recipientsName == null ? null : recipientsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.remark
     *
     * @return the value of order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.remark
     *
     * @param remark the value for order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.send_address
     *
     * @return the value of order.send_address
     *
     * @mbg.generated
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.send_address
     *
     * @param sendAddress the value for order.send_address
     *
     * @mbg.generated
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress == null ? null : sendAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.send_full_address
     *
     * @return the value of order.send_full_address
     *
     * @mbg.generated
     */
    public String getSendFullAddress() {
        return sendFullAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.send_full_address
     *
     * @param sendFullAddress the value for order.send_full_address
     *
     * @mbg.generated
     */
    public void setSendFullAddress(String sendFullAddress) {
        this.sendFullAddress = sendFullAddress == null ? null : sendFullAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sender_landline_number
     *
     * @return the value of order.sender_landline_number
     *
     * @mbg.generated
     */
    public String getSenderLandlineNumber() {
        return senderLandlineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sender_landline_number
     *
     * @param senderLandlineNumber the value for order.sender_landline_number
     *
     * @mbg.generated
     */
    public void setSenderLandlineNumber(String senderLandlineNumber) {
        this.senderLandlineNumber = senderLandlineNumber == null ? null : senderLandlineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sender_mobile
     *
     * @return the value of order.sender_mobile
     *
     * @mbg.generated
     */
    public String getSenderMobile() {
        return senderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sender_mobile
     *
     * @param senderMobile the value for order.sender_mobile
     *
     * @mbg.generated
     */
    public void setSenderMobile(String senderMobile) {
        this.senderMobile = senderMobile == null ? null : senderMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sender_name
     *
     * @return the value of order.sender_name
     *
     * @mbg.generated
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sender_name
     *
     * @param senderName the value for order.sender_name
     *
     * @mbg.generated
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }
}