package com.kuaidixx.kuaidixx.dao;

import com.kuaidixx.kuaidixx.pojo.payinfo;
import java.util.List;

public interface payinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int insert(payinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    payinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    List<payinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(payinfo record);
}